### PR TITLE
More realistic

### PR DESCRIPTION
**Pull request by Kiffolisk**
Make the website more realistic by making it generate a random number when clicking a button. Also updated the README.

### CODE REVIEW

**Comment by chrislo27** [comment]
To help me review this PR more effectively, could you please publish your fork's GitHub Page by going into the Settings and setting the root to be built? That way I could check it at https://kiffolisk.github.io/rh-this-year/. Much appreciated.


image

**Comment by Kiffolisk** [comment]
I have done that, but for some reason it says "Site not found". Might have to wait a bit, don't really know. It says it has been published, so I don't know why it says "Site not found".

**Comment by Kiffolisk** [comment]
Ok, managed to fix it.

**Review by chrislo27 — APPROVED** [review]

**Comment by chrislo27** [comment]
Thanks for your pull request, it has been merged. Changes should show up on https://chrislo27.github.io/rh-this-year/ within 24 hours.

**Pull request merged**
